# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
