# Generated by Django 2.0.2 on 2018-02-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='owner',
            new_name='added_by',
        ),
    ]
