# Generated by Django 2.0.2 on 2018-05-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20180228_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
