# Generated by Django 2.0.2 on 2018-05-17 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_music_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='title_cache_time',
            field=models.DateTimeField(default=datetime.datetime(2010, 1, 1, 0, 0), verbose_name='Cache time of title'),
        ),
    ]
