# Generated by Django 2.0.4 on 2018-05-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_auto_20180516_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position in queue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='date_added',
            field=models.DateTimeField(db_index=True, verbose_name='date added'),
        ),
    ]
